name: kai_zen
description: Hide/block social apps using accessibility + overlay (Kai-zen)
publish_to: 'none'
version: 0.3.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  installed_apps: ^1.1.0
  shared_preferences: ^2.0.17
  intl: ^0.18.0
  google_fonts: ^5.0.0
  flutter_local_notifications: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf